name: "Yarn Install"
description: "Install Node dependencies with Yarn"
author: "eric phung"

inputs:
  node-version:
    description: "Node.js version"
    default: "22"
    required: false
  working-directory:
    description: "Where package.json is located"
    default: "."
    required: false
  install-args:
    description: "Extra args for yarn install (optional)"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock

    - name: Cache Yarn Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable
        yarn install --immutable ${{ inputs.install-args }}
